#!/bin/bash

help() {
  echo "Usage:"
  echo "  zjump restart"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  ensure_config

  zmicro plugin run compose restart $PLUGIN_JUMP_NAME
}

run() {
  core $@
}

run $@
